{% set name = "apache-airflow-providers-apache-beam" %}
{% set version = "6.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_apache_beam-{{ version }}.tar.gz
  sha256: b62e843235afd0bea1d46e152eb3057b5e7a4c51af0f99ed185ac33d3ee8108a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.10.0
    - apache-beam >=2.60.0
    - pyarrow >=16.1.0
    # using the most restrictive so we can be noarch: python
    - numpy >=1.26.0

test:
  imports:
    - airflow.providers.apache.beam
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apache-beam for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/apache/beam/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-beam/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
