{% set name = "apache-airflow-providers-apache-beam" %}
{% set version = "5.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_apache_beam-{{ version }}.tar.gz
  sha256: 761fcaad6522a46a9512c9863de4bd65c7063df7a831df77625c02c95ae4c5ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.9,<4.dev0
    - apache-airflow >=2.8.0
    - apache-beam >=2.53.0
    - pyarrow >=14.0.1

test:
  imports:
    - airflow.providers.apache.beam
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apache-beam for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/apache/beam/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-beam/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
