{% set name = "apache-airflow-providers-apache-beam" %}
{% set version = "6.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_apache_beam-{{ version }}.tar.gz
  sha256: 8a13cde9e8bb48abbdb4351ee03fc4ad8fdc38b800bdce9164dde8f8f274e24a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }},<3.13
    - apache-airflow >=2.10.0
    # more restrictive for python <3.13
    - apache-beam >=2.60.0
    # more restrictive for python <3.13
    - pyarrow >=16.1.0
    # more restrictive for python >=3.12
    - numpy >=1.26.0

test:
  imports:
    - airflow.providers.apache.beam
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apache-beam for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-beam/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
